# Generated by Django 5.1.3 on 2024-11-13 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("callculator", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Billing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="call",
            name="duration",
            field=models.DurationField(blank=True, null=True),
        ),
    ]
